--
-- PostgreSQL database dump
--

-- Dumped from database version 14.6 (Debian 14.6-1.pgdg110+1)
-- Dumped by pg_dump version 14.6 (Debian 14.6-1.pgdg110+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Job; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public."Job" (
    "Id" integer NOT NULL,
    "Name" text NOT NULL,
    "UserId" integer NOT NULL
);


ALTER TABLE public."Job" OWNER TO "user";

--
-- Name: Job_Id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public."Job" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Job_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: User; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public."User" (
    "Id" integer NOT NULL,
    "FirstName" text NOT NULL
);


ALTER TABLE public."User" OWNER TO "user";

--
-- Name: User_Id_seq; Type: SEQUENCE; Schema: public; Owner: user
--

ALTER TABLE public."User" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."User_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: user
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO "user";

--
-- Data for Name: Job; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public."Job" ("Id", "Name", "UserId") FROM stdin;
2	job1	1
1	job2	1
\.


--
-- Data for Name: User; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public."User" ("Id", "FirstName") FROM stdin;
1	user1
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: user
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20230101063853_InitialCreate	7.0.1
\.


--
-- Name: Job_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public."Job_Id_seq"', 4, true);


--
-- Name: User_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: user
--

SELECT pg_catalog.setval('public."User_Id_seq"', 1, true);


--
-- Name: Job PK_Job; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public."Job"
    ADD CONSTRAINT "PK_Job" PRIMARY KEY ("Id");


--
-- Name: User PK_User; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "PK_User" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_Job_UserId; Type: INDEX; Schema: public; Owner: user
--

CREATE INDEX "IX_Job_UserId" ON public."Job" USING btree ("UserId");


--
-- Name: Job FK_Job_User_UserId; Type: FK CONSTRAINT; Schema: public; Owner: user
--

ALTER TABLE ONLY public."Job"
    ADD CONSTRAINT "FK_Job_User_UserId" FOREIGN KEY ("UserId") REFERENCES public."User"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

