version: '3'
volumes:
  exclude:
  pgsqldata:

services:
  pgsql:
    image: postgres:14
    platform: linux/x86-64
    tty: true
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
      TZ: ${TZ}
    ports:
      - ${DB_PORT}:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "||", "exit", "1"]
      interval: 2s
      timeout: 5s
      retries: 5
    volumes:
      - ./pgsql/data:/var/lib/postgresql/data
    # command: mysqld --innodb_use_native_aio=0
