FROM node:18.10-bullseye

WORKDIR /app
COPY ./backend/package.json .
COPY ./backend/yarn.lock .
RUN yarn install --frozen-lockfile && yarn cache clean
ENV PATH=/app/node_modules/.bin:$PATH

WORKDIR /app/dev
COPY ./backend/tsconfig.json .
COPY ./backend/src ./src
COPY ./backend/prisma ./prisma
EXPOSE 3000
CMD ["yarn", "dev"]
