version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  db-data:
    driver: local
  mysql-data:

services:
  web:
    image: nginx:alpine
    container_name: blnweb
    env_file:
      - ./.env
    ports:
      - 80:80
    volumes:
      - ./html:/var/www/html
      - ./logs/nginx/:/var/log/nginx
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
  app:
    build: ./php
    container_name: blnapp
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: blndb
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --general-log=true
      --general-log-file=/var/log/mysql/general.log
    env_file:
      - ./.env
    ports:
      - 3306:3306
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
      - ./mysql-data:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: blnpma
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=user
      - PMA_PASSWORD=password
    links:
      - mysql
    ports:
      - 8080:80
    volumes:
      - /sessions
