version: '3'
services:
  web:
    image: php:7.4-apache
    ports:
      - '80:80'
    depends_on:
      - app
    volumes:
      - ./html:/var/www/html
    container_name: php
  app:
    build: ./docker/php
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mysql
    container_name: app
  mysql:
    image: mysql/mysql-server:5.7.28
    environment:
      MYSQL_DATABASE: platon
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql-init:/docker-entrypoint-initdb.d
      - ./db/mysql-data:/var/lib/mysql
      - ./db/logs:/var/log/mysql
      - ./db/ddl:/work
    container_name: mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql:db
    ports:
      - 8080:80
    volumes:
      - /sessions
    container_name: phpmyadmin
volumes:
  mysql-data:
