version: '3'
services:
  mysql:
    image: mysql/mysql-server:8.0.23
    environment:
      MYSQL_DATABASE: stub
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./db/ddl:/work
    container_name: mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - mysql:db
    ports:
      - 8080:80
    volumes:
      - /sessions
    container_name: phpmyadmin
volumes:
  mysql-data:
